# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # name our filter set "my_thumb_filter"
        post_list_filter:
            quality: 75
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [100, 80]
                    # crop the input image, if required
                    mode: outbound
        post_thumbnail:
            quality: 75
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [600, 280]
                    # crop the input image, if required
                    mode: outbound
        post_gallery:
            quality: 75
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [600, 600]
                    # crop the input image, if required
                    mode: outbound
