twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes:
        [
            "bootstrap_5_layout.html.twig",
            "@FOSCKEditor/Form/ckeditor_widget.html.twig",
        ]
when@test:
    twig:
        strict_variables: true
        form_themes: ["bootstrap_5_layout.html.twig"]

fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - {
                      name: "styles",
                      items:
                          [
                              "Bold",
                              "Italic",
                              "Underline",
                              "Strike",
                              "Blockquote",
                              "-",
                              "Link",
                              "-",
                              "RemoveFormat",
                              "-",
                              "NumberedList",
                              "BulletedList",
                              "-",
                              "Outdent",
                              "Indent",
                              "-",
                              "-",
                              "JustifyLeft",
                              "JustifyCenter",
                              "JustifyRight",
                              "JustifyBlock",
                              "-",
                              "Table",
                              "-",
                              "Styles",
                              "Format",
                              "Font",
                              "FontSize",
                              "-",
                              "TextColor",
                              "BGColor",
                              "Source",
                          ],
                  }
