vich_uploader:
    db_driver: orm
    # Add php8 native attribute #[annotation] support instead of old @annotation parser
    metadata:
        type: attribute

    mappings:
        post_thumbnail:
            uri_prefix: /images/posts
            upload_destination: "%kernel.project_dir%/public/images/posts"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
