version: "3.8"

services:
    db:
        image: mysql
        container_name: db_sfuploads
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmnin_sfuploads
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    www:
        build: docker
        container_name: www_sfuploads
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        networks:
            - dev

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
        networks:
            - dev

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
