name: Symfony

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest
        steps:
            #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
            # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
            # uses: shivammathur/setup-php@v2
            - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
              with:
                  php-version: "8.1"
            - uses: actions/checkout@v3

            - name: Copy .env.test.local
              run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install Dependencies
              run: composer install --no-interaction --no-progress

            # Install Symfony CLI
            - name: Symfony CLI
              run: |
                  curl -sS https://get.symfony.com/cli/installer | bash
                  mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
            # Check vulnerabilities
            - name: Symfony Check Vulnerabilities
              run: symfony check:security

            # PHP CS FIXER
            - name: PHP-CS-Fixer
              run: |
                  composer require friendsofphp/php-cs-fixer
                  ./vendor/bin/php-cs-fixer fix
            # PHP STAN
            - name: PHP Stan
              run: |
                  ./vendor/bin/simple-phpunit install
                  composer require phpstan/phpstan
                  composer require phpstan/extension-installer
                  composer config --no-plugins allow-plugins.phpstan/extension-installer true
                  composer require phpstan/phpstan-symfony
                  ./vendor/bin/phpstan analyse src --memory-limit 1G
            - name: Lint YAML files
              run: ./bin/console lint:yaml config --parse-tags

            - name: Lint Twig templates
              run: ./bin/console lint:twig templates --env=prod

            - name: Lint Parameters and Services
              run: ./bin/console lint:container --no-debug

            - name: Lint Doctrine entities
              run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            - name: Create Database
              run: |
                  mkdir -p data
                  touch data/database.sqlite

            - name: Migrate database
              run: .bin/console d:m:m --no-interaction --env=test

            - name: Loading fixtures
              run: ./bin/console d:f:l --no-interaction --env=test

            - name: Execute tests (Unit and Feature tests) via PHPUnit
              env:
                  DATABASE_URL: sqlite:///%kernel.project_dir%/var/database_test.db
              run: vendor/bin/phpunit
