name: Pipeline-CI
on:
    push:
        branches: [main]

permissions:
    contents: read
    # Needed for the 'trilom/file-changes-action' action
    pull-requests: read

jobs:
    ci:
        runs-on: ubuntu-latest
        continue-on-error: false
        env:
            DB_DATABASE: webapp_test
            DB_USERNAME: symfony
            DB_PASSWORD: password
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: true
                    MYSQL_DATABASE: webapp_test
                    MYSQL_USER: symfony
                    MYSQL_PASSWORD: password
                    MYSQL_ROOT_PASSWORD: password
                ports:
                    - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              id: yarn-cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-cache-node-modules-

            - name: Yarn install
              if: steps.yarn-cache-node-modules.outputs.cache-hit != 'true'
              run: yarn install

            - name: Yarn build
              run: yarn run encore

            # https://github.com/shivammathur/setup-php (community)
            - name: Setup PHP, extensions and composer with shivammathur/setup-php
              uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
              with:
                  php-version: "8.1"
                  extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, curl, libxml, zip, pcntl, sqlite, pdo_sqlite, bcmath, soap, intl, exif,
            # Composer .env.test
            # - name: Copy .env.test
            #   run: cp .env.test.local .env

            # Npm install dependencies
            - name: "Composer install"
            - run: npm install

            # Npm build
            - run: npm run build

            - name: Cache multiple paths
              uses: actions/cache@v2
              with:
                  path: |
                      vendor
                      node_modules
                  key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

            # Composer install
            - name: "Composer install"
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            # Install Symfony CLI
            - name: Symfony CLI
              run: |
                  curl -sS https://get.symfony.com/cli/installer | bash
                  mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

            # Composer install
            - name: "Composer install"
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            # Check vulnerabilities
            - name: Symfony Check Vulnerabilities
              run: symfony check:security

            # PHP CS FIXER
            - name: PHP-CS-Fixer
              run: |
                  composer require friendsofphp/php-cs-fixer
                  ./vendor/bin/php-cs-fixer fix

            # PHP STAN
            - name: PHP Stan
              run: |
                  ./vendor/bin/simple-phpunit install
                  composer require phpstan/phpstan
                  composer require phpstan/extension-installer
                  composer config --no-plugins allow-plugins.phpstan/extension-installer true
                  composer require phpstan/phpstan-symfony
                  ./vendor/bin/phpstan analyse src --memory-limit 1G

            - name: Lint YAML files
              run: ./bin/console lint:yaml config --parse-tags

            - name: Lint Twig templates
              run: ./bin/console lint:twig templates --env=prod

            - name: Lint Parameters and Services
              run: ./bin/console lint:container --no-debug

            - name: Lint Doctrine entities
              run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

            - name: Run Migration && Fixtures
              run: |
                  composer require --dev symfony/orm-pack
                  php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
                  php bin/console doctrine:migrations:migrate --no-interaction --env=test || echo "No migrations found or migration failed"
                  php bin/console doctrine:fixtures:load --no-interaction --env=test
              env:
                  DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/webapp

            - name: PHP Unit
              env:
                  DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/webapp
              run: ./bin/phpunit --testdox
